export interface Job {
  id: string;
  title: string;
  company: string;
  initial: string;
  location: string;
  salary: string;
  postedDaysAgo: number;
  level: "Entry-level" | "Mid-level" | "Senior";
  type: "Full-time" | "Internship" | "Part-time" | "Contract";
  category: string;
  description: string;
  requirements: string[];
  deadline: string;
  companyEmployees: string;
  verifiedEmployer: boolean;
}

export const jobs: Job[] = [
  {
    id: "frontend-engineer-kaziflow",
    title: "Frontend Engineer",
    company: "Kaziflow Technologies",
    initial: "K",
    location: "Lagos, Nigeria",
    salary: "₦450,000 - ₦650,000/mo",
    postedDaysAgo: 9,
    level: "Mid-level",
    type: "Full-time",
    category: "Technology",
    description:
      "Build and maintain user-facing features for our fintech platform, working closely with design and backend teams.",
    requirements: [
      "3+ years with React and TypeScript",
      "Experience with REST APIs",
      "Strong eye for UI detail",
      "Comfortable in a fast-moving startup",
    ],
    deadline: "2026-08-05",
    companyEmployees: "51-200 employees",
    verifiedEmployer: true,
  },
  {
    id: "data-analyst-intern-savanna",
    title: "Data Analyst Intern",
    company: "Savanna Analytics",
    initial: "S",
    location: "Nairobi, Kenya",
    salary: "KSh 40,000/mo stipend",
    postedDaysAgo: 13,
    level: "Entry-level",
    type: "Internship",
    category: "Data & AI",
    description:
      "Support the analytics team with data cleaning, reporting, and dashboard building for East African clients.",
    requirements: [
      "Familiarity with Excel or SQL",
      "Currently studying a quantitative field",
      "Strong attention to detail",
    ],
    deadline: "2026-07-28",
    companyEmployees: "11-50 employees",
    verifiedEmployer: true,
  },
  {
    id: "branch-credit-officer-baobab",
    title: "Branch Credit Officer",
    company: "Baobab Microfinance Group",
    initial: "B",
    location: "Accra, Ghana",
    salary: "GH₵ 4,500 - 6,000/mo",
    postedDaysAgo: 18,
    level: "Mid-level",
    type: "Full-time",
    category: "Finance",
    description:
      "Assess loan applications, manage a portfolio of micro-enterprise clients, and support financial literacy programs in your assigned branch.",
    requirements: [
      "Diploma or degree in Finance, Business, or Economics",
      "2+ years in microfinance or retail banking",
      "Strong local language skills",
      "Motorcycle license preferred",
    ],
    deadline: "2026-07-30",
    companyEmployees: "201-500 employees",
    verifiedEmployer: true,
  },
  {
    id: "agronomy-field-officer-sahara",
    title: "Agronomy Field Officer",
    company: "Sahara Agritech",
    initial: "S",
    location: "Cape Town, South Africa",
    salary: "R22,000 - R28,000/mo",
    postedDaysAgo: 25,
    level: "Mid-level",
    type: "Contract",
    category: "Agriculture",
    description:
      "Work directly with smallholder farmers to improve crop yields using Sahara Agritech's precision farming tools.",
    requirements: [
      "Degree in Agriculture or related field",
      "Field experience with smallholder farmers",
      "Willingness to travel regionally",
    ],
    deadline: "2026-08-12",
    companyEmployees: "51-200 employees",
    verifiedEmployer: false,
  },
  {
    id: "logistics-coordinator-nile",
    title: "Logistics Coordinator",
    company: "Nile Logistics Co.",
    initial: "N",
    location: "Kigali, Rwanda",
    salary: "RWF 900,000 - 1,200,000/mo",
    postedDaysAgo: 10,
    level: "Mid-level",
    type: "Full-time",
    category: "Logistics",
    description:
      "Coordinate freight schedules, manage warehouse inventory, and liaise with cross-border transport partners.",
    requirements: [
      "2+ years in supply chain or logistics",
      "Proficiency with inventory software",
      "Strong organizational skills",
    ],
    deadline: "2026-08-02",
    companyEmployees: "201-500 employees",
    verifiedEmployer: true,
  },
  {
    id: "clinical-officer-safiri",
    title: "Clinical Officer",
    company: "Safiri Health",
    initial: "S",
    location: "Kigali, Rwanda",
    salary: "RWF 700,000 - 950,000/mo",
    postedDaysAgo: 6,
    level: "Senior",
    type: "Full-time",
    category: "Healthcare",
    description:
      "Provide outpatient care at a community clinic, working alongside nurses and visiting specialists.",
    requirements: [
      "Valid clinical officer license",
      "3+ years post-qualification experience",
      "Comfortable working in rural clinics",
    ],
    deadline: "2026-08-01",
    companyEmployees: "51-200 employees",
    verifiedEmployer: true,
  },
  {
    id: "social-media-intern-jollof",
    title: "Social Media Intern",
    company: "Jollof Media House",
    initial: "J",
    location: "Lagos, Nigeria",
    salary: "₦80,000/mo stipend",
    postedDaysAgo: 2,
    level: "Entry-level",
    type: "Internship",
    category: "Media",
    description:
      "Assist the content team with scheduling posts, tracking engagement, and drafting captions across platforms.",
    requirements: [
      "Active on Instagram, TikTok, and X",
      "Basic Canva or CapCut skills",
      "Excellent written English",
    ],
    deadline: "2026-08-10",
    companyEmployees: "11-50 employees",
    verifiedEmployer: false,
  },
  {
    id: "solar-technician-brightgrid",
    title: "Solar Installation Technician",
    company: "BrightGrid Energy",
    initial: "B",
    location: "Kampala, Uganda",
    salary: "UGX 1,200,000 - 1,600,000/mo",
    postedDaysAgo: 15,
    level: "Mid-level",
    type: "Full-time",
    category: "Energy",
    description:
      "Install and maintain off-grid solar systems for rural households and small businesses across the region.",
    requirements: [
      "Certification in electrical or solar installation",
      "1+ years hands-on field experience",
      "Valid driver's license",
    ],
    deadline: "2026-08-08",
    companyEmployees: "51-200 employees",
    verifiedEmployer: true,
  },
  {
    id: "front-desk-agent-zanzibar",
    title: "Front Desk Agent",
    company: "Zanzibar Bay Resorts",
    initial: "Z",
    location: "Zanzibar, Tanzania",
    salary: "TSh 600,000 - 800,000/mo",
    postedDaysAgo: 4,
    level: "Entry-level",
    type: "Part-time",
    category: "Hospitality",
    description:
      "Welcome guests, manage check-in/check-out, and handle reservations for a beachfront boutique resort.",
    requirements: [
      "Fluent in English and Swahili",
      "Friendly, guest-first attitude",
      "Flexible weekend availability",
    ],
    deadline: "2026-07-29",
    companyEmployees: "11-50 employees",
    verifiedEmployer: false,
  },
  {
    id: "store-supervisor-marketmax",
    title: "Store Supervisor",
    company: "MarketMax Retail",
    initial: "M",
    location: "Cairo, Egypt",
    salary: "EGP 8,000 - 11,000/mo",
    postedDaysAgo: 20,
    level: "Mid-level",
    type: "Full-time",
    category: "Retail",
    description:
      "Oversee daily store operations, manage staff schedules, and drive sales targets for a growing retail chain.",
    requirements: [
      "2+ years retail supervisory experience",
      "Strong leadership and communication",
      "Comfortable with POS systems",
    ],
    deadline: "2026-08-06",
    companyEmployees: "501-1000 employees",
    verifiedEmployer: true,
  },
  {
    id: "hr-generalist-chipper",
    title: "HR Generalist",
    company: "Chipper Cash",
    initial: "C",
    location: "Kigali, Rwanda",
    salary: "RWF 1,100,000 - 1,400,000/mo",
    postedDaysAgo: 7,
    level: "Mid-level",
    type: "Full-time",
    category: "Human Resources",
    description:
      "Support recruitment, onboarding, and employee relations for a fast-growing fintech team across East Africa.",
    requirements: [
      "3+ years in HR or people operations",
      "Experience with HRIS platforms",
      "Strong interpersonal skills",
    ],
    deadline: "2026-08-14",
    companyEmployees: "201-500 employees",
    verifiedEmployer: true,
  },
  {
    id: "backend-engineer-paystash",
    title: "Backend Engineer (Node.js)",
    company: "Paystash",
    initial: "P",
    location: "Nairobi, Kenya",
    salary: "KSh 180,000 - 250,000/mo",
    postedDaysAgo: 12,
    level: "Senior",
    type: "Full-time",
    category: "Technology",
    description:
      "Design and scale backend services powering cross-border payments for small businesses in East Africa.",
    requirements: [
      "4+ years with Node.js and PostgreSQL",
      "Experience with payment systems a plus",
      "Strong understanding of API security",
    ],
    deadline: "2026-08-09",
    companyEmployees: "51-200 employees",
    verifiedEmployer: true,
  },
  {
    id: "graphic-designer-jumia",
    title: "Graphic Designer",
    company: "Jumia",
    initial: "J",
    location: "Cairo, Egypt",
    salary: "EGP 12,000 - 16,000/mo",
    postedDaysAgo: 5,
    level: "Mid-level",
    type: "Contract",
    category: "Media",
    description:
      "Create visual assets for marketing campaigns, product banners, and social media across multiple markets.",
    requirements: [
      "Portfolio demonstrating brand/campaign work",
      "Proficiency in Figma and Adobe Creative Suite",
      "Ability to work across tight deadlines",
    ],
    deadline: "2026-08-03",
    companyEmployees: "1000+ employees",
    verifiedEmployer: true,
  },
  {
    id: "software-engineer-intern-mkopa",
    title: "Software Engineer Intern",
    company: "M-KOPA",
    initial: "M",
    location: "Nairobi, Kenya",
    salary: "KSh 45,000/mo stipend",
    postedDaysAgo: 3,
    level: "Entry-level",
    type: "Internship",
    category: "Technology",
    description:
      "Join the mobile team building IoT-connected solar and device financing products for underserved households.",
    requirements: [
      "Currently studying Computer Science or related field",
      "Basic knowledge of Kotlin or Java",
      "Eagerness to learn in a mentorship-driven team",
    ],
    deadline: "2026-08-11",
    companyEmployees: "1000+ employees",
    verifiedEmployer: true,
  },
];